# Generated by Django 3.1.1 on 2021-04-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sessionsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
