# Generated by Django 3.1.1 on 2021-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iworkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
            ],
        ),
    ]
