# Generated by Django 3.1.1 on 2021-04-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_service_provide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ihuzo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('Fullname', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Iworkers',
        ),
        migrations.DeleteModel(
            name='MSMEs',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Service_provide',
        ),
    ]
