# Generated by Django 3.1.1 on 2021-06-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210419_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ihuzo',
            new_name='Msmes',
        ),
    ]
