# Generated by Django 3.1.1 on 2021-06-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210607_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msmes',
            name='sector',
        ),
    ]
